# Generated by Django 4.0.2 on 2022-02-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='game_category',
            old_name='game_id',
            new_name='game',
        ),
    ]
