# Generated by Django 4.0.2 on 2022-02-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating_for_game',
            field=models.ManyToManyField(related_name='rating_for_game', through='gamerraterapi.Rating', to='gamerraterapi.Player'),
        ),
    ]
