# Generated by Django 4.0.2 on 2022-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0004_rename_name_player_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(related_name='categories', through='gamerraterapi.Game_Category', to='gamerraterapi.Category'),
        ),
    ]
