# Generated by Django 4.0.2 on 2022-02-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0005_remove_game_category_game_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(null=True, upload_to='pictures')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='gamerraterapi.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
