# Generated by Django 4.0.2 on 2022-02-12 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0006_gamepicture_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepicture',
            name='base64',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamepicture',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gamerraterapi.player'),
            preserve_default=False,
        ),
    ]
